spring.application.name=google-contacts

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=email, profile, https://www.googleapis.com/auth/contacts


logging.level.org.springframework.security=DEBUG